In [23]:
# ライブラリ
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder  #文字列を 数値に変換
from sklearn.ensemble import RandomForestRegressor  #回帰モデル（価格予測)

In [24]:
# 1 データ読み込み
train = pd.read_csv("train.tsv", sep="\t")
test = pd.read_csv("test.tsv", sep="\t")

In [25]:
# 2. データ確認
train.head()
train.info()
train.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1482535 entries, 0 to 1482534
Data columns (total 8 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   train_id           1482535 non-null  int64
 1   name               1482535 non-null  object
 2   item_condition_id  1482535 non-null  int64
 3   category_name      1476208 non-null  object
 4   brand_name         849853 non-null   object
 5   price              1482535 non-null  float64
 6   shipping           1482535 non-null  int64
 7   item_description   1482529 non-null  object
dtypes: float64(1), int64(3), object(4)
memory usage: 90.5+ MB

           train_id  item_condition_id         price      shipping
count  1.482535e+06       1.482535e+06  1.482535e+06  1.482535e+06
mean   7.412670e+05       1.907380e+00  2.673752e+01  4.472744e-01
std    4.279711e+05       9.031586e-01  3.858607e+01  4.972124e-01
min    0.000000e+00       1.000000e+00  0.000000e+00  0.000000e+00
25%    3.706335e+05       1.000000e+00  1.000000e+01  0.000000e+00
50%    7.412670e+05       2.000000e+00  1.700000e+01  0.000000e+00
75%    1.111900e+06       3.000000e+00  2.900000e+01  1.000000e+00
max    1.482534e+06       5.000000e+00  2.009000e+03  1.000000e+00

In [26]:
# 3. 欠損確認
train.isnull().sum()

train_id                  0
name                      0
item_condition_id         0
category_name          6327
brand_name           632682
price                     0
shipping                  0
item_description          6
dtype: int64

In [27]:
# 4. 欠損箇所処理
for col in ["category_name","brand_name","item_description"]:
    train[col] = train[col].fillna("None")
    test[col] = test[col].fillna("None")

In [28]:
# 5. 再確認
train.isnull().sum()

train_id             0
name                 0
item_condition_id    0
category_name        0
brand_name           0
price                0
shipping             0
item_description     0
dtype: int64

In [29]:
# 6 カテゴリ変数の数値化
le_brand = LabelEncoder()
le_cat = LabelEncoder()

le_brand.fit(pd.concat([train["brand_name"], test["brand_name"]]))
train["brand_name"] = le_brand.transform(train["brand_name"])
test["brand_name"] = le_brand.transform(test["brand_name"])

le_cat.fit(pd.concat([train["category_name"], test["category_name"]]))
train["category_name"] = le_cat.transform(train["category_name"])
test["category_name"] = le_cat.transform(test["category_name"])

In [ ]:
# 7. 説明変数作成
drop_cols = ["train_id","name","item_description","price"]

X = train.drop(drop_cols, axis=1)
y = train["price"]

test_X = test.drop(["test_id","name","item_description"], axis=1)

In [30]:
# 8. モデル作成
model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

model.fit(X,y)

RandomForestRegressor(random_state=42)

In [31]:
# 6 予測
pred = model.predict(test_X)

In [32]:
# 7 提出ファイル
submission = pd.DataFrame({
    "test_id":test["test_id"],
    "price":pred
})

submission.to_csv("submission2.csv",index=False)

print("submission.csv を保存しました")

submission.csv を保存しました

In [33]:
from google.colab import files
files.download("submission2.csv")